apiVersion: config.kueue.x-k8s.io/v1beta1
kind: Configuration
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: :8080
# enableClusterQueueResources: true
webhook:
  port: 9443
leaderElection:
  leaderElect: false
controller:
  groupKindConcurrency:
    Job.batch: 100
    Pod: 100
    Workload.kueue.x-k8s.io: 100
    LocalQueue.kueue.x-k8s.io: 100
    Cohort.kueue.x-k8s.io: 100
    ClusterQueue.kueue.x-k8s.io: 100
    ResourceFlavor.kueue.x-k8s.io: 100
clientConnection:
  qps: 1000
  burst: 1000
#pprofBindAddress: :8083
#waitForPodsReady:
#  enable: false
#  timeout: 5m
#  blockAdmission: false
#  requeuingStrategy:
#    timestamp: Eviction
#    backoffLimitCount: null # null indicates infinite requeuing
#    backoffBaseSeconds: 60
#    backoffMaxSeconds: 3600
#manageJobsWithoutQueueName: true
#managedJobsNamespaceSelector:
#  matchLabels:
#    kueue-managed: "true"
#internalCertManagement:
#  enable: false
#  webhookServiceName: ""
#  webhookSecretName: ""
integrations:
  frameworks:
  - "batch/job"
# - "kubeflow.org/mpijob"
# - "ray.io/rayjob"
# - "ray.io/raycluster"
# - "jobset.x-k8s.io/jobset"
# - "kubeflow.org/mxjob"
# - "kubeflow.org/paddlejob"
# - "kubeflow.org/pytorchjob"
# - "kubeflow.org/tfjob"
# - "kubeflow.org/xgboostjob"
#  - "pod"
#  - "deployment" # requires enabling pod integration
#  - "statefulset" # requires enabling pod integration
#  externalFrameworks:
#  - "Foo.v1.example.com"
#  podOptions:
#    namespaceSelector:
#      matchExpressions:
#        - key: kubernetes.io/metadata.name
#          operator: NotIn
#          values: [ kube-system, kueue-system ]
#fairSharing:
#  enable: true
#  preemptionStrategies: [LessThanOrEqualToFinalShare, LessThanInitialShare]
#resources:
#  excludeResourcePrefixes: []
#  transformations:
#  - input: nvidia.com/mig-4g.5gb
#    strategy: Replace | Retain
#    outputs:
#      example.com/accelerator-memory: 5Gi
#      example.com/accelerator-gpc: 4
