apiVersion: v1
kind: Service
metadata:
  labels:
    component: kube-apiserver-audit-exporter
  name: monitoring-kube-apiserver-audit-exporter
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: kube-apiserver-audit-exporter
  type: ClusterIP
