# Source: kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: monitoring-kube-prometheus-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "69.3.2"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-69.3.2
    release: "monitoring"
    heritage: "Helm"
spec:
  image: "kind-registry:5000/quay.io/prometheus/alertmanager:v0.28.0"
  version: v0.28.0
  replicas: 1
  listenLocal: false
  serviceAccountName: monitoring-kube-prometheus-alertmanager
  automountServiceAccountToken: true
  externalUrl: http://monitoring-kube-prometheus-alertmanager.monitoring:9093
  paused: false
  logFormat: "logfmt"
  logLevel: "info"
  retention: "120h"
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - {key: app.kubernetes.io/name, operator: In, values: [alertmanager]}
            - {key: alertmanager, operator: In, values: [monitoring-kube-prometheus-alertmanager]}
  portName: http-web
