apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-alertmanager
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 69.3.2
    chart: kube-prometheus-stack-69.3.2
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-alertmanager
  namespace: monitoring
