# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: monitoring-kube-prometheus-prometheus
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus

    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "69.3.2"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-69.3.2
    release: "monitoring"
    heritage: "Helm"
spec:
  automountServiceAccountToken: true
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: monitoring-kube-prometheus-alertmanager
      port: http-web
      pathPrefix: "/"
      apiVersion: v2
  image: "m.daocloud.io/quay.io/prometheus/prometheus:v3.1.0"
  version: v3.1.0
  externalUrl: http://monitoring-kube-prometheus-prometheus.monitoring:9090
  paused: false
  replicas: 1
  shards: 1
  logLevel: info
  logFormat: logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  tsdb:
    outOfOrderTimeWindow: 0s
  walCompression: true
  routePrefix: "/"
  serviceAccountName: monitoring-kube-prometheus-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: "monitoring"

  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "monitoring"

  podMonitorNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: "monitoring"

  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: "monitoring"

  scrapeConfigSelector:
    matchLabels:
      release: "monitoring"

  scrapeConfigNamespaceSelector: {}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - {key: app.kubernetes.io/name, operator: In, values: [prometheus]}
            - {key: prometheus, operator: In, values: [monitoring-kube-prometheus-prometheus]}
  portName: http-web
  hostNetwork: false
