apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress-nginx_serviceaccount.yaml
- ingress-nginx_role.yaml
- ingress-nginx_rolebinding.yaml
- controller_service.yaml
- controller-admission_service.yaml
- controller_deployment.yaml
- nginx_ingressclass.yaml

configMapGenerator:
- name: ingress-nginx-controller
  namespace: ingress-nginx
  options:
    disableNameSuffixHash: true
    labels:
      "app.kubernetes.io/name": "ingress-nginx"
      "app.kubernetes.io/part-of": "ingress-nginx"
      "app.kubernetes.io/version": "1.12.0"
      "app.kubernetes.io/component": "controller"
      "app.kubernetes.io/instance": "ingress-nginx"
  files:
