apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: coscheduling
data:
  scheduler-config.yaml: |-
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
      resourceNamespace: coscheduling
      resourceName: scheduler-plugins-scheduler
    profiles:
    # Compose all plugins in one profile
    - schedulerName: coscheduling
      plugins:
        multiPoint:
          enabled:
          - name: Coscheduling
          disabled:
          - name: CapacityScheduling
          - name: NodeResourceTopologyMatch
          - name: NodeResourcesAllocatable
          - name: PrioritySort
      pluginConfig:
      - args:
          permitWaitingTimeSeconds: 10
        name: Coscheduling
