apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-plugins-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - topology.node.k8s.io
  resources:
  - noderesourcetopologies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.x-k8s.io
  resources:
  - podgroups
  - elasticquotas
  - podgroups/status
  - elasticquotas/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
