apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yunikorn
    chart: yunikorn-1.6.2
    heritage: Helm
    release: yunikorn
  name: yunikorn-admission-controller
  namespace: yunikorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yunikorn
      component: yunikorn-admission-controller
      release: yunikorn
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: null
      labels:
        app: yunikorn
        component: yunikorn-admission-controller
        release: yunikorn
      name: yunikorn-admission-controller
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: kind-registry:5000/docker.io/apache/yunikorn:admission-1.6.2
        imagePullPolicy: IfNotPresent
        name: yunikorn-admission-controller
        ports:
        - containerPort: 9089
          name: webhook-api
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: webhook-api
            scheme: HTTPS
          periodSeconds: 5
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: webhook-api
            scheme: HTTPS
          periodSeconds: 10
        volumeMounts:
        - mountPath: /run/secrets/webhook
          name: admission-controller-secrets
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      serviceAccountName: yunikorn-admission-controller
      terminationGracePeriodSeconds: 1
      volumes:
      - name: admission-controller-secrets
        secret:
          secretName: admission-controller-secrets
