apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yunikorn
    chart: yunikorn-1.6.2
    heritage: Helm
    release: yunikorn
  name: yunikorn-scheduler
  namespace: yunikorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yunikorn
      component: yunikorn-scheduler
      release: yunikorn
  template:
    metadata:
      annotations: null
      labels:
        app: yunikorn
        component: yunikorn-scheduler
        release: yunikorn
      name: yunikorn-scheduler
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: kind-registry:5000/docker.io/apache/yunikorn:scheduler-1.6.2
        imagePullPolicy: IfNotPresent
        name: yunikorn-scheduler-k8s
        ports:
        - containerPort: 9080
          name: http1
          protocol: TCP
      serviceAccountName: yunikorn-admin
      terminationGracePeriodSeconds: 1

