apiVersion: v1
kind: Service
metadata:
  labels:
    app: kwok-controller
  name: kwok-controller
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 10247
    protocol: TCP
    targetPort: 10247
  selector:
    app: kwok-controller
  type: ClusterIP
