apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "2"
  name: yunikorn-admission-controller-rbac
  namespace: yunikorn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yunikorn-admission-controller-role
subjects:
- kind: ServiceAccount
  name: yunikorn-admission-controller
  namespace: yunikorn
