# Source: kube-prometheus-stack/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.9.1
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "11.5.1"
data:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC
    [server]
    root_url = /grafana/
    serve_from_sub_path = true
    [auth]
    disable_login = true
    disable_login_form = true
    disable_signout_menu = true
    [auth.anonymous]
    enabled = true
    org_role = Editor
    hide_version = true
