apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana
- prometheus-operator-webhook
- alertmanager
- prometheus-operator
- prometheus
- metrics
- kube-prometheus-stack-prometheus
- kube-prometheus-stack-grafana
- kube-prometheus-stack-alertmanager
- kube-prometheus-stack-coredns
- kube-prometheus-stack-kube-controller-manager
- kube-prometheus-stack-kube-etcd
- kube-prometheus-stack-kube-proxy
- kube-prometheus-stack-kube-scheduler
- kube-prometheus-stack
- kube-prometheus-stack-apiserver
- kube-prometheus-stack-kubelet
- namespace.yaml
