apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "0"
  name: volcano-admission-init-role
  namespace: volcano-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: volcano-admission-init
subjects:
- kind: ServiceAccount
  name: volcano-admission-init
  namespace: volcano-system
