apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "0"
  name: volcano-admission-init
  namespace: volcano-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - patch
  - get
