apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- role.yaml
- clusterrole.yaml
- rolebinding.yaml
- clusterrolebinding.yaml
- service.yaml
- deployment.yaml
- servicemonitor.yaml

configMapGenerator:
- name: monitoring-grafana
  namespace: monitoring
  options:
    disableNameSuffixHash: true
    labels:
      "app.kubernetes.io/instance": "monitoring"
      "app.kubernetes.io/name": "grafana"
      "app.kubernetes.io/version": "11.5.1"
      "helm.sh/chart": "grafana-8.9.1"
  files:
  - grafana.ini
- name: monitoring-grafana-config-dashboards
  namespace: monitoring
  options:
    disableNameSuffixHash: true
    labels:
      "app.kubernetes.io/version": "11.5.1"
      "helm.sh/chart": "grafana-8.9.1"
      "app.kubernetes.io/instance": "monitoring"
      "app.kubernetes.io/name": "grafana"
  files:
  - provider.yaml

secretGenerator:
- name: monitoring-grafana
  namespace: monitoring
  type: Opaque
  options:
    disableNameSuffixHash: true
    labels:
      "app.kubernetes.io/instance": "monitoring"
      "app.kubernetes.io/name": "grafana"
      "app.kubernetes.io/version": "11.5.1"
      "helm.sh/chart": "grafana-8.9.1"
  files:
  - admin-password
  - admin-user
  - ldap-toml
