apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.5.1
    helm.sh/chart: grafana-8.9.1
  name: monitoring-grafana
  namespace: monitoring
spec:
  ports:
  - name: http-web
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
  type: ClusterIP
