apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.5.1
    helm.sh/chart: grafana-8.9.1
    release: monitoring
  name: monitoring-grafana
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-web
    scheme: http
    scrapeTimeout: 30s
  jobLabel: monitoring
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/name: grafana
