apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.5.1
    helm.sh/chart: grafana-8.9.1
  name: monitoring-grafana
  namespace: monitoring
