apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kube-state-metrics_serviceaccount.yaml
- prometheus-node-exporter_serviceaccount.yaml
- kube-state-metrics_clusterrole.yaml
- kube-state-metrics_clusterrolebinding.yaml
- kube-state-metrics_service.yaml
- prometheus-node-exporter_service.yaml
- kube-state-metrics_deployment.yaml
- prometheus-node-exporter_daemonset.yaml
- kube-state-metrics_servicemonitor.yaml
- prometheus-node-exporter_servicemonitor.yaml
