apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kwok-controller
- node-heartbeat-with-lease.yaml
- node-initialize.yaml
- pod-complete.yaml
- pod-delete.yaml
- pod-ready.yaml
